### ISSUE TITLE
Error in script Palette_inspector_script.gd

### ISSUE THREAD

**Issue by sancho2** [RancidMilkGames/GodotPaletteTools#1]
There is an error in this script.   
Line 3 should read: 
var custom_palette_property = preload("res://addons/PaletteTools/scripts/custom_property.gd")     
   
The installation installs that script in ../PaletteTools/script (lowercase s)   

on Linux/Ubuntu

**Comment by RancidMilkGames** [comment]
I've renamed the Scripts folder to the appropriate casing. You mentioned in the other issue #2  you were having other problems, but you'll have to be specific as it works out of the box on Windows 10 and 11, even when the folder was wrongly cased. I'll look into trying it in a Linux VM later to see if I can find other issues.

**Comment by RancidMilkGames** [comment]
I tried it in Ubuntu with Godot 4.2 beta 3 and it works as intended. If you specify more about what problems you're running into, I can try to help.

**Comment by sancho2** [comment]
I tried again installing it on a new project in Godot 4.2 via the AssetLibrary.    
The first thing I notice is a message about 3 conflicting files: 2 git files gitignore and gitattributes and the project file project.godot. I have no idea what that is about.    
Next I see a boat load of errors in the messages window:    
Godot Engine v4.2.dev5.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  res://addons/PaletteTools/scripts/palette_inspector_script.gd:3 - Parse Error: Preload file "res://addons/PaletteTools/Scripts/custom_property.gd" does not exist.
  res://addons/PaletteTools/scripts/palette_inspector_script.gd:3 - Parse Error: Could not resolve type for variable "custom_palette_property".
  modules/gdscript/gdscript.cpp:2656 - Failed to load script "res://addons/PaletteTools/scripts/palette_inspector_script.gd" with error "Parse error". (User)
  Attempt to open script 'res://addons/PaletteTools/Scripts/palette_tool.gd' resulted in error 'File not found'.
  Failed loading resource: res://addons/PaletteTools/Scripts/palette_tool.gd. Make sure resources have been imported by opening the project in the editor at least once.
  Attempt to open script 'res://addons/PaletteTools/Scripts/get_from_url.gd' resulted in error 'File not found'.
  Failed loading resource: res://addons/PaletteTools/Scripts/get_from_url.gd. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://addons/PaletteTools/Scenes/palette_tools.tscn:153 - Parse Error: 
  Failed loading resource: res://addons/PaletteTools/Scenes/palette_tools.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/PaletteTools/palette_tools.gd:14 - Parse Error: Preload file "res://addons/PaletteTools/Scripts/palette_inspector_script.gd" does not exist.
  modules/gdscript/gdscript.cpp:2656 - Failed to load script "res://addons/PaletteTools/palette_tools.gd" with error "Parse error". 

   
The plugin shows up under plugins in the project manager but when I try to enable it I get these errors:   
 _Attempt to open script 'res://addons/PaletteTools/Scripts/palette_tool.gd' resulted in error 'File not found'.
  Failed loading resource: res://addons/PaletteTools/Scripts/palette_tool.gd. Make sure resources have been imported by opening the project in the editor at least once.
  Attempt to open script 'res://addons/PaletteTools/Scripts/get_from_url.gd' resulted in error 'File not found'.
  Failed loading resource: res://addons/PaletteTools/Scripts/get_from_url.gd. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://addons/PaletteTools/Scenes/palette_tools.tscn:153 - Parse Error: 
  Failed loading resource: res://addons/PaletteTools/Scenes/palette_tools.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/PaletteTools/palette_tools.gd:14 - Parse Error: Preload file "res://addons/PaletteTools/Scripts/palette_inspector_script.gd" does not exist.
  modules/gdscript/gdscript.cpp:2656 - Failed to load script "res://addons/PaletteTools/palette_tools.gd" with error "Parse error".   core/config/project_settings.cpp:341 - Property not found: editor_plugins/enabled_


The addon files are all there in the folders as designated. For example the first error regarding 'palette_tool.gd  File not found'; that file is there and the path is correct.    
   
I have used your plugin on a Windows machine and it works flawlessly. Thank you for that.    
I would really like to get this to work on this machine as well.

**Comment by sancho2** [comment]
Edit:   
I found it. If anyone else is having an issue there is a tab added to the top of the node inspector.   
The new tab is not visible by default so you have to click the little arrow beside "Inspector Node History   < >"   

...
So I installed again in another new project and repeated the errors as describe prior.    
I went back and repopened the other project and the addin begins working.     
However I can see no way to download palette files.  
I get the custom color picker showing and it shows 'no saved palettes'. But I don't see any menu item relating to downloading palette from lospec.

**Comment by RancidMilkGames** [comment]
I would recommend you get it from here at the moment, as I haven't applied for an update in the asset library since making that folder casing change earlier today.

Do the errors appear again after restarting the project? Unfortunately a lot of Godot addons produce a list of errors when first added, but then don't show up on subsequent loads. 

> Make sure resources have been imported by opening the project in the editor at least once.

This message, which appears next to all those errors, is saying that you need to load it once. It's a very common message when adding a plugin for the first time. Again, it shouldn't appear in future loads. I'm guessing it's just trying to read the files before it's aware it has them.

And referring to your comment:
> 3 conflicting files: 2 git files gitignore and gitattributes and the project file project.godot

I can restructure the addon so this doesn't happen, but then it no longer works as a full sample project when downloaded. Many addons also have at least the project.godot part so people can just see it's use in a sample project.

This was taken on a 4k display, which is why sizing might appear slightly off:
![image](https://github.com/RancidMilkGames/GodotPaletteTools/assets/115530728/b7fdfefd-08ed-45ff-a005-5efb4a84afdc)
Just enter your Lospec palette link there and hit the little search icon or enter, and it'll grab the palette.
