### ISSUE TITLE
Error in script palette_tools.gd

### ISSUE THREAD

**Issue by sancho2** [RancidMilkGames/GodotPaletteTools#2]
Line 14 should read: 

	inspector_palette_plugin = preload("res://addons/PaletteTools/scripts/palette_inspector_script.gd").new(self)     
    
Again, lowercase s in /scripts
   
Unfortunately there are other issues as well, some relating to the lowercase error and others I could not figure out.   
Was not able to get this working on Ubuntu using GODOT 4.2.

**Comment by RancidMilkGames** [comment]
Duplicate of #1
