### ISSUE TITLE
After install: error in palette_inspector_script.gd:33 - Trying to assign value of type 'Color' to a variable of type 'String'

### ISSUE THREAD

**Issue by hsandt** [RancidMilkGames/GodotPaletteTools#5]
After install, I got this once:

> res://addons/PaletteTools/Scripts/palette_inspector_script.gd:33 - Trying to assign value of type 'Color' to a variable of type 'String'

in `func initial_palette():`

but it doesn't seem to reoccur. Just a one-time error because `preset_settings` had the wrong types of values?

**Comment by RancidMilkGames** [comment]
I just made a new project and downloaded it (4.2+ version) from the asset library, and did not get this error. I will need more info on how to recreate it. I'm closing it for now, but if you can give the steps to make this happen again, and it is affecting functionality, I will reopen this. If it's just an error that appears once and doesn't affect anything, it might be related to how Godot parses addons the first time.
