### ISSUE TITLE
Entering lospec palette name or URL and clicking on magnifier glass button does nothing

### ISSUE THREAD

**Issue by hsandt** [RancidMilkGames/GodotPaletteTools#6]
![image](https://github.com/RancidMilkGames/GodotPaletteTools/assets/1067772/42f3fe0e-8599-44c6-96a6-3ae48ec5f844)

I clicked on the magnifier class button but nothing happened. I can only Browse Palettes but the browse popup has no name filter, making it very long to scroll and find the palette when I already know the name.

If either direct URL, or name filtering worked, it would be much faster to get it done.

**Comment by RancidMilkGames** [comment]
You need to provide more information for bugs like this, as it works for me:
![image](https://github.com/RancidMilkGames/GodotPaletteTools/assets/115530728/3af473ef-d93e-45d4-b5ff-6c8c7056b5cd)

Like what OS are you on, what Godot version are you using, which version of the addon you're using (4+ vs 4.2+), etc.

**Comment by RancidMilkGames** [comment]
Update with either minimal recreation conditions or required information for a bug report and issue will be reopened.
